# Generated by Django 4.2.5 on 2023-11-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultureType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ReqTempC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ReqHum', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'culture_type',
            },
        ),
        migrations.CreateModel(
            name='HeatingModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heatingMode', models.CharField(max_length=100)),
                ('curState', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'HeatingModule',
            },
        ),
        migrations.CreateModel(
            name='IrrigationModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('irrigationMode', models.CharField(max_length=100)),
                ('curState', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'IrrigationModule',
            },
        ),
        migrations.CreateModel(
            name='LightingModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lightingMode', models.CharField(max_length=100)),
                ('curState', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LightingModule',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.TimeField()),
                ('ReqAction', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='VentilationModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ventilationMode', models.CharField(max_length=100)),
                ('curState', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'VentilationModule',
            },
        ),
        migrations.CreateModel(
            name='SmartModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curState', models.CharField(max_length=100)),
                ('HeatModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.heatingmodule')),
                ('VentModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.ventilationmodule')),
                ('irrigModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.irrigationmodule')),
                ('lightModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.lightingmodule')),
            ],
            options={
                'db_table': 'Time_schedule',
            },
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GH_Name', models.CharField(max_length=100, unique=True)),
                ('Area_m2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.culturetype')),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.schedule')),
                ('SmartModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.smartmodule')),
            ],
            options={
                'db_table': 'greenhouse',
            },
        ),
    ]
