# Generated by Django 4.1 on 2022-09-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultureType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('ReqTempC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ReqHum', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'culture_type',
            },
        ),
        migrations.CreateModel(
            name='TnTData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Time_', models.TimeField()),
                ('Temperature_C', models.DecimalField(decimal_places=2, max_digits=5))
            ],
            options={
                'db_table': 'TnTdata',
            },
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GH_Name', models.CharField(max_length=255, null=False, unique=True)),
                ('Area_m2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.CultureType')),
                ('TnTData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.TnTData')),
            ],
            options={
                'db_table': 'greenhouse',
            },
        ),
    ]
