# Generated by Django 4.2.5 on 2023-10-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culturetype',
            old_name='Name',
            new_name='CulName',
        ),
        migrations.RenameField(
            model_name='tntdata',
            old_name='Time_',
            new_name='Time',
        ),
    ]
