# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghapp', '0002_rename_name_culturetype_culname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tntdata',
            table='Tnt data',
        ),
    ]
