# Generated by Django 4.2.5 on 2023-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghapp', '0003_alter_tntdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.TimeField()),
                ('ReqAction', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Time_schedule',
            },
        ),
        migrations.RenameField(
            model_name='culturetype',
            old_name='CulName',
            new_name='name',
        ),
    ]
