# Generated by Django 4.2.5 on 2023-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghapp', '0004_timeschedule_rename_culname_culturetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='OkAnswer',
            field=models.CharField(default='Not ok', max_length=255),
        ),
    ]
