# Generated by Django 4.2.5 on 2023-10-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghapp', '0005_timeschedule_okanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturetype',
            name='ReqHum',
        ),
        migrations.RemoveField(
            model_name='culturetype',
            name='ReqTempC',
        ),
    ]
