# Generated by Django 5.0.1 on 2024-01-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('Area_m2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Greenhouse',
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ReqHum', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Plant type',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BeginTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('TimePeriods', models.TimeField()),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='SmartModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heatModule', models.BooleanField(default=True)),
                ('ventModule', models.BooleanField(default=True)),
                ('lightModule', models.BooleanField(default=True)),
                ('irrigModule', models.BooleanField(default=True)),
                ('curState', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Smart module',
            },
        ),
        migrations.CreateModel(
            name='GreenhouseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TemperatureC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CurPressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.greenhouse')),
            ],
            options={
                'db_table': 'Greenhouse data',
            },
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='Plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.planttype'),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='Schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.schedule'),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='SmartModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghapp.smartmodule'),
        ),
    ]
